# Makefile for Chapter 9 Programs
# Template Functions

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: max1 max2 max3 max4 max5 tf1 tf2 exports swap eqsize countval \
#ptf1 ptf2 
ptf3 memset dim2 dim2s transp
#################################################################
# max() template functions
max1: max1.exe

max2: max2.exe
max2.exe: max2.obj String.obj
	$(CC) $(CFLAGS) max2.obj String.obj
max2.obj String.obj: String.h

max3: max3.exe
max3.exe: max3.obj String.obj
	$(CC) $(CFLAGS) max3.obj String.obj
max3.obj String.obj: String.h

max4: max4.exe
max4.exe: max4.obj String.obj
	$(CC) $(CFLAGS) max4.obj String.obj
max4.obj String.obj: String.h
#################################################################
# template functions
tf1: tf1.exe
tf2: tf2.exe
countval: countval.exe
countval.exe: countval.obj String.obj
	$(CC) $(CFLAGS) countval.obj String.obj
exports: exports.exe
exports.exe: defs.h
#################################################################
# swap(), eqsize() template functions
swap: swap.exe
swap.exe: swap.obj String.obj
	$(CC) $(CFLAGS) swap.obj String.obj
swap.obj String.obj: String.h

eqsize: eqsize.exe
eqsize.exe: eqsize.obj String.obj
	$(CC) $(CFLAGS) eqsize.obj String.obj
eqsize.obj String.obj: String.h
#################################################################
# ptf(), pointers to functions
ptf1: ptf1.exe

ptf2: ptf2.exe
ptf2.exe: ptf2.obj String.obj
	$(CC) $(CFLAGS) ptf2.obj String.obj
ptf2.obj String.obj: String.h

ptf3: ptf3.exe
ptf3.exe: ptf3.obj String.obj
	$(CC) $(CFLAGS) ptf3.obj String.obj
ptf3.obj String.obj: String.h
#################################################################
# overloading template functions
ov1: ov1.exe
ov1.exe: ov1.obj String.obj
	$(CC) $(CFLAGS) ov1.obj String.obj
ov1.obj String.obj: String.h
#################################################################
# specializing template functions
spm: spm.exe

max5: max5.exe
max5.exe: max5.obj String.obj
	$(CC) $(CFLAGS) max5.obj String.obj
max5.obj String.obj: String.h

memset: memset.exe
memset.exe: memset.obj String.obj
	$(CC) $(CFLAGS) memset.obj String.obj
memset.obj String.obj: String.h Complex.h
#################################################################
# dim2() template function
# Two-dimensional arrays at run time
dim2: dim2.exe
dim2.exe: dim2.h

dim2s: dim2s.exe
dim2s.exe: dim2.h Complex.h
#################################################################
# transpose() template function
transp: transp.exe
transp.exe: transp.obj String.obj
	$(CC) $(CFLAGS) transp.obj String.obj
String.obj: String.h
transp.obj: String.h dim2.h transpos.h
#################################################################
clean:
	del *.obj
	del *.exe
