# Makefile for Chapter 12 Programs
# RTTI (Run Time Type Identification)

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: invest1 invest2 invest3 invest4 invest5 \
typ1 typ2 typ3 typ4 \
shape1 shape2 pitems \
pwrite pread
#################################################################
# Investment class
invest1: invest1.exe
invest1.exe: Invest1.h

invest2: invest2.exe
invest2.exe: Invest2.h

invest3: invest3.exe
invest3.exe: Invest3.h

invest4: invest4.exe
invest4.exe: Invest4.h

invest5: invest5.exe
invest5.exe: Invest5.h
#################################################################
# Typeid() operator
typ1: typ1.exe
typ1.exe: typ1.obj String.obj
	$(CC) $(CFLAGS) typ1.obj String.obj
typ1.obj: String.h Complex.h Array.h Array.C
String.obj: String.h

typ2: typ2.exe
typ2.exe: Invest4.h

typ3: typ3.exe
typ3.exe: typ3.obj String.obj
	$(CC) $(CFLAGS) typ3.obj String.obj
typ3.obj: Invest5.h String.h

typ4: typ4.exe
typ4.exe: typ4.obj String.obj
	$(CC) $(CFLAGS) typ4.obj String.obj
typ4.obj: Array.h Array.C String.h
#################################################################
# Shape programs
shape1: shape1.exe
shape1.exe: shape1.obj String.obj
	$(CC) $(CFLAGS) shape1.obj String.obj
shape1.obj: Shape.h List.h List.C PtrList.h

shape2: shape2.exe
shape2.exe: shape2.obj String.obj
	$(CC) $(CFLAGS) shape2.obj String.obj
shape2.obj: Shape.h List.h List.C PtrList.h
#################################################################
# Publish items
pitems: pitems.exe
pitems.exe: pitems.obj String.obj
	$(CC) $(CFLAGS) pitems.obj String.obj
pitems.obj: Publish.h String.h
#################################################################
# Persistence programs
pwrite: pwrite.exe
pwrite.exe: pwrite.obj persist.obj String.obj
	$(CC) $(CFLAGS) pwrite.obj persist.obj String.obj
pwrite.obj: Solid.h List.h List.C PtrList.h String.h Assoc.h \
Assoc.C Array.h Array.C Persist.h pwrite.C
persist.obj: Solid.h Persist.h persist.C

pread: pread.exe
pread.exe: pread.obj persist.obj String.obj
	$(CC) $(CFLAGS) pread.obj persist.obj String.obj
pread.obj: Solid.h List.h List.C PtrList.h String.h Assoc.h \
Assoc.C Array.h Array.C Persist.h pread.C
#################################################################
clean:
	del *.obj
	del *.exe
