# Makefile for Chapter 4 Exercises
# Classes

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = dates cfifo5 rnum2 rnum3 cfifo6 record2 points

all: $(PGMS)
#################################################################
# Exercise 1
dates: dates.o Date.o
	$(CC) $(CFLAGS) dates.o Date.o -o dates
dates.o Date.o: Date.h

# Exercise 2
cfifo5: cfifo5.o Fifo5.o
	$(CC) $(CFLAGS) cfifo5.o Fifo5.o -o cfifo5
cfifo5.o Fifo5.o: Fifo5.h

# Exercise 3
rnum2: rnum2.o Roman2.o
	$(CC) $(CFLAGS) rnum2.o Roman2.o -o rnum2
rnum2.o Roman2.o: Roman2.h

# Exercise 4
rnum3: rnum3.o Roman3.o
	$(CC) $(CFLAGS) rnum3.o Roman3.o -o rnum3
rnum3.o Roman3.o: Roman3.h

# Exercise 5
cfifo6: cfifo6.o Fifo6.o
	$(CC) $(CFLAGS) cfifo6.o Fifo6.o -o cfifo6
cfifo6.o Fifo6.o: Fifo6.h

# Exercise 6
record2: record2.o StringN.o
	$(CC) $(CFLAGS) record2.o StringN.o -o record2
record2.o: Record2.h StringN.h

# Exercise 7 
points: points.o Point6.o
	$(CC) $(CFLAGS) points.o Point6.o -o points
points.o Point6.o: Point6.h
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
