# Makefile for Chapter 3 Programs
# C++ Program Structure

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = com func itoh fact calc a1d a2d a3d defarg debug debug2 scmp \
struct1 struct2 struct3 mutable itoh2 bitf ref pxchg1 pxchg2 mod1 \
mymath1 mymath2 mymath3 unnamed1 unnamed2 unnamed3 nest nalias ns1 ns2 \
ns3 ns4 ns5 ns6 ns7 \
hypot setnh money bmove

all: $(PGMS)
#################################################################
# Command line arguments
com: com.C

# Function prototypes
func: func.C

# Recursive functions
itoh: itoh.C
fact: fact.C

# Pointers to functions
calc: calc.C
	$(CC) $(CFLAGS) calc.C -o calc -lm

# Arrays as function arguments
a1d: a1d.C
a2d: a2d.C
a3d: a3d.C

# Default Arguments
debug: debug.o error.o
	$(CC) $(CFLAGS) debug.o error.o -o debug
debug.o error.o: error.h

debug2: debug2.o error2.o
	$(CC) $(CFLAGS) debug2.o error2.o -o debug2
debug2.o error2.o: error2.h

# Standard Args
scmp: scmp.C

# Structures
struct1: struct1.C
struct2: struct2.C
struct3: struct3.C

# Mutable
mutable: mutable.C

# Namespaces
mymath1: mymath1.o geo1.o
mymath1.o geo1.o: geo1.h

mymath2: geo2.h

mymath3: mymath3.o geometry.o
	$(CC) $(CFLAGS) mymath3.o geometry.o -o mymath3
mymath3.o geometry.o: geometry.h

ns1: ns1.C
ns2: ns2.C
ns3: ns3.C
ns4: ns4.C
ns5: ns5.C
ns6: ns6.C
ns7: ns7.C
unnamed1: unnamed1.C
unnamed2: unnamed2.C
unnamed3: unnamed3.C
nest: nest.C
nalias: nalias.C

# Unions
itoh2: itoh2.C
	$(CC) $(CFLAGS) -DINTEL itoh2.C -o itoh2

# Bitfields
bitf: bitf.C

# Constant reference arguments
ref: ref.C

# References to pointers
pxchg1: pxchg1.C
pxchg2: pxchg2.C

# Extern and modules
mod1: mod1.o mod2.o
	$(CC) $(CFLAGS) mod1.o mod2.o -o mod1
mod1.o mod2.o: global.h

# Exceptions
hypot: hypot.C
	$(CC) $(CFLAGS) hypot.C -o hypot -lm

# set_new_handler
setnh: setnh.C

# Enumerated types and const references
money: money.C

# Optimized block moves
bmove: bmove.C
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
