# Makefile for Chapter 8 Exercises
# Object Storage Management

CC = bcc
CFLAGS = -P -O
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

PGMS = mp1 mleak ctext cassign s1

all: $(PGMS)
#################################################################
# Exercise 1
# see exer1.txt

# Exercise 2
mp1: mp1.exe
mp1.exe: A1.h Mpool.h

# Exercise 3
mleak: mleak.exe
mleak.exe: mleak.obj New.obj
	$(CC) $(CFLAGS) mleak.obj New.obj
mleak.obj: New.h mleak.C
	$(CC) $(CFLAGS) -c -DMLEAK mleak.C
New.obj: New.h New.C
	$(CC) $(CFLAGS) -c -DMLEAK New.C

# Exercise 4
ctext: ctext.exe
ctext.exe: ctext.obj String.obj
	$(CC) $(CFLAGS) ctext.obj String.obj
ctext.obj: cText.h Text.h String.h
String.obj: String.h

# Exercise 5
cassign: cassign.exe
cassign.exe: cassign.obj String.obj
	$(CC) $(CFLAGS) cassign.obj String.obj
cassign.obj: cText.h Text.h String.h

# Exercise 6
s1: s1.exe
s1.exe: s1.obj StringN.obj
	$(CC) $(CFLAGS) s1.obj StringN.obj
s1.obj: cStringN.h StringN.h
StringN.obj: StringN.h
#################################################################
clean:
	del *.obj
	del *.exe
