# Makefile for Chapter 2 Programs
# C++ Basics

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: wchart cast1 cast6 cast7 comma comma2 block scope switch1 switch2 \
goto lvrv macro1 macro2 typeid void2 fruits
#################################################################
# data types
wchart: wchart.exe

# cast and conversions
cast1: cast1.exe
cast6: cast6.exe
cast7: cast7.exe

# comma operator
comma: comma.exe
comma2: comma2.exe

# blocks, scope operator
block: block.exe
scope: scope.exe

# switch construct
switch1: switch1.exe
switch2: switch2.exe

# goto
goto: goto.exe

# lvalues and rvalues
lvrv: lvrv.exe

# macros
macro1: macro1.exe
macro2: macro2.exe

# typeid operator
typeid: typeid.exe

# void pointers
void2: void2.exe

# putting it all together
fruits: fruits.exe
#################################################################
clean:
	del *.obj
	del *.exe
