# Makefile for Appendix B
# Standard Template Library (STL)

CC = CC
CFLAGS = -O -ptused -n32 -OPT:Olimit=2816 -experimental

.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = find1 algo1 vec1 vec2 list1 list2 deque1 queue1 stack1 map1 ptrlist1 \
ptrlist2 ptrlist3

all: $(PGMS)
#####################################################################
# Generic Algorithms
find1: find1.C
algo1: algo1.C

# Vector
vec1: vec1.C
vec2: vec2.C

# List
list1: list1.C
list2: list2.C

# Deque
deque1: deque1.C

# Queue
queue1: queue1.C

# Stack
stack1: stack1.C

# Map
map1: map1.C
#####################################################################
# Pointer List
ptrlist1: Shape.h ptrlist1.C
	$(CC) $(CFLAGS) ptrlist1.C -o ptrlist1 -lm
ptrlist2: Shape.h ptrlist2.C
	$(CC) $(CFLAGS) ptrlist2.C -o ptrlist2 -lm
ptrlist3: Shape.h ptrlist3.C
	$(CC) $(CFLAGS) ptrlist3.C -o ptrlist3 -lm
#####################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
