# Makefile for Chapter 4 Programs
# Classes

CC = bcc
CFLAGS = -P -O
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

all: cfifo1 cfifo2 cfifo3 cfifo4 cfifo5 file1 file2 movies \
	  point1 point2 circle act1 act s1 record record2
#################################################################
# Fifo class
cfifo1: cfifo1.exe
cfifo1.exe: Fifo1.h

cfifo2: cfifo2.exe
cfifo2.exe: Fifo2.h

cfifo3: cfifo3.exe
cfifo3.exe: Fifo3.h

cfifo4: cfifo4.exe
cfifo4.obj Fifo4.obj: Fifo4.h
cfifo4.exe: cfifo4.obj Fifo4.obj
	$(CC) $(CFLAGS) cfifo4.obj Fifo4.obj

cfifo5: cfifo5.exe
cfifo5.obj Fifo5.obj: Fifo5.h
cfifo5.exe: cfifo5.obj Fifo5.obj
	$(CC) $(CFLAGS) cfifo5.obj Fifo5.obj
#################################################################
# File class
file1: file1.exe
file1.exe: File1.h

file2: file2.exe
file2.exe: File2.h
#################################################################
# Roman class
movies: movies.exe
movies.obj Roman.obj: Roman.h
movies.exe: movies.obj Roman.obj
	$(CC) $(CFLAGS) movies.obj Roman.obj
#################################################################
# Point class
point1: point1.exe
point2: point2.exe
#################################################################
# StringN and Record class
s1: s1.exe
s1.obj Stringn.obj: Stringn.h
s1.exe: s1.obj Stringn.obj
	$(CC) $(CFLAGS) s1.obj Stringn.obj

record: record.exe
record.obj: Record.h Stringn.h
record.exe: record.obj Stringn.obj
	$(CC) $(CFLAGS) record.obj Stringn.obj

record2: record2.exe
record2.obj: Record2.h Stringn.h
record2.exe: record2.obj Stringn.obj
	$(CC) $(CFLAGS) record2.obj Stringn.obj
#################################################################
circle: circle.exe

act: act.exe
act.obj: Roman.h Fifo5.h
act.exe: act.obj Roman.obj fifo5.obj
	$(CC) $(CFLAGS) act.obj Roman.obj fifo5.obj

act1: act1.exe
act1.obj: Roman.h Fifo5.h
act1.exe: act1.obj Roman.obj fifo5.obj
	$(CC) $(CFLAGS) act1.obj Roman.obj fifo5.obj
#################################################################
clean:
	del *.obj
	del *.exe
