# Makefile for Chapter 3 Programs
# C++ Program Structure

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: com func itoh fact calc a1d a2d a3d defarg debug debug2 scmp \
struct1 struct2 struct3 itoh2 bitf ref pxchg1 pxchg2 mod1 mutable \
mymath1 mymath2 mymath3 unnamed1 unnamed2 unnamed3 nest nalias \
ns1 ns2 ns3 ns4 ns5 ns6 ns7 hypot setnh money bmoves
#################################################################
# Command line arguments
com: com.exe

# Function prototypes
func: func.exe

# Recursive functions
itoh: itoh.exe
fact: fact.exe

# Pointers to functions
calc: calc.exe

# Arrays as function arguments
a1d: a1d.exe
a2d: a2d.exe
a3d: a3d.exe

# Default Arguments
defarg: defarg.exe
debug: debug.exe
debug.exe: debug.obj error.obj
	$(CC) $(CFLAGS) debug.obj error.obj
debug.obj error.obj: error.h

debug2: debug2.exe
debug2.exe: debug2.obj error2.obj
	$(CC) $(CFLAGS) debug2.obj error2.obj
debug2.obj error2.obj: error2.h

# Standard Args
scmp: scmp.exe

# Structures
struct1: struct1.exe
struct2: struct2.exe
struct3: struct3.exe

# Unions
itoh2: itoh2.exe

# Bitfields
bitf: bitf.exe

# Constant reference arguments
ref: ref.exe

# References to pointers
pxchg1: pxchg1.exe
pxchg2: pxchg2.exe

# Extern and modules
mod1: mod1.exe
mod1.exe: mod1.obj mod2.obj
	$(CC) $(CFLAGS) mod1.obj mod2.obj
mod1.obj mod2.obj: global.h

# Mutable
mutable: mutable.exe

# Namespaces
mymath1: mymath1.obj geo1.obj
mymath1.obj: geo1.h
geo1.obj: geo1.h

mymath2: mymath2.exe
mymath2.exe: geo2.h

mymath3: mymath3.exe
mymath3.exe: mymath3.obj geometry.obj
	$(CC) $(CFLAGS) mymath3.obj geometry.obj 
mymath3.obj: geometry.h
geometry.obj: geometry.h

ns1: ns1.exe
ns2: ns2.exe
ns3: ns3.exe
ns4: ns4.exe
ns5: ns5.exe
ns6: ns6.exe
ns7: ns7.exe
unnamed1: unnamed1.exe
unnamed2: unnamed2.exe
unnamed3: unnamed3.exe
nest: nest.exe
nalias: nalias.exe

# Exceptions
hypot: hypot.exe

# set_new_handler
setnh: setnh.exe

# Enumerated types and const references
money: money.exe

# Optimized block moves
bmoves: bmoves.exe
#################################################################
clean:
	del *.obj
	del *.exe
