# Makefile for Chapter 10 Exercises
# Template Classes

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = tstack1 tstack2 a1d a2d newdata gfifo1 gfifo2 gfifo3 \
transp a4d tblock2 fs1 sp1 zip2 zip3 plist na1 na2 na3 bt

all: $(PGMS)
#################################################################
# Exercise 1
tstack1: tstack1.o String.o
	$(CC) $(CFLAGS) tstack1.o String.o -o tstack1
tstack1.o: Stack1.h String.h
String.o: String.h

# Exercise 2
tstack2: Stack2.h Array.h Array.C

# Exercise 3
a1d: Array.h Array.C

a2d: Array.h Array.C Array2d.h

# Exercise 4
newdata: newdata.o String.o
	$(CC) $(CFLAGS) newdata.o String.o -o newdata
newdata.o: String.h

# Exercise 5
gfifo1: FifoChr.h Fifo.h Array.h Array.C

# Exercise 6
gfifo2: Fifo.h Array.h Array.C

# Exercise 7
gfifo3: gfifo3.o String.o
	$(CC) $(CFLAGS) gfifo3.o String.o -o gfifo3
gfifo3.o: String.h Fifo2.h List.h List.C

# Exercise 8
transp: transpos.h Array2d.h Array.h Array.C

# Exercise 9
a4d: Array4d.h Array3d.h Array2d.h Array.h Array.C

# Exercise 10 
tblock2: tblock2.o String.o
	$(CC) $(CFLAGS) tblock2.o String.o -o tblock2
tblock2.o: String.h Block2.h

# Exercise 11 
fs1: FString1.h

# Exercise 12 
sp1: sp1.o String.o
	$(CC) $(CFLAGS) sp1.o String.o -o sp1
sp1.o: Ptr.h String.h

# Exercise 13 
zip2: zip2.o String.o
	$(CC) $(CFLAGS) zip2.o String.o -o zip2
zip2.o: Assoc2.h Array.h String.h Assoc2.C Array.C

# Exercise 14 
zip3: zip3.o String.o
	$(CC) $(CFLAGS) zip3.o String.o -o zip3
zip3.o: Assoc2.h Array.h String.h Assoc2.C Array.C

# Exercise 15 
plist: plist.o String.o
	$(CC) $(CFLAGS) plist.o String.o -o plist
plist.o: List.h List.C String.h

# Exercise 16
bt: bt.o String.o
	$(CC) $(CFLAGS) bt.o String.o -o bt
bt.o: Btree.h String.h

# Exercise 17
na1: nArray.h nArray.C
na2: nArray.h nArray.C
na3: nArray.h nArray.C
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
