# Makefile for Chapter 5 Programs
# Working with Classes

CC = bcc
CFLAGS = -P -O
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

all: efifo iblock point3 point4 point5 decades objects arrays concalls \
plist1 plistn plistn2 local namelib forties
#################################################################
# Explicit
efifo: efifo.exe
efifo.obj Fifo5.obj: Fifo5.h
efifo.exe: efifo.obj Fifo5.obj
	$(CC) $(CFLAGS) efifo.obj Fifo5.obj

iblock: iblock.exe

# Roman class
decades: decades.exe
decades.obj Roman2.obj: Roman2.h
decades.exe: decades.obj Roman2.obj
	$(CC) $(CFLAGS) decades.obj Roman2.obj

objects: objects.exe
objects.obj Roman3.obj: Roman3.h
objects.exe: objects.obj Roman3.obj
	$(CC) $(CFLAGS) objects.obj Roman3.obj

arrays: arrays.exe
arrays.obj Roman4.obj: Roman4.h
arrays.exe: arrays.obj Roman4.obj
	$(CC) $(CFLAGS) arrays.obj Roman4.obj
concalls: concalls.exe
#################################################################
# Point class
point3: point3.exe
point3.exe: Point3.h

point4: point4.exe

point5: point5.exe
point5.exe: Point5.h
#################################################################
# List class
plist1: plist1.exe
plist1.obj List1.obj: List1.h
plist1.exe: plist1.obj List1.obj
	$(CC) $(CFLAGS) plist1.obj List1.obj

plistn: plistn.exe
plistn.obj Listn.obj: Listn.h
plistn.exe: plistn.obj Listn.obj
	$(CC) $(CFLAGS) plistn.obj Listn.obj

plistn2: plistn2.exe
plistn2.obj Listn2.obj: Listn2.h
plistn2.exe: plistn2.obj Listn2.obj
	$(CC) $(CFLAGS) plistn2.obj Listn2.obj
#################################################################
# Local classes
local: local.exe
#################################################################
# Namespaces and Classes
forties: forties.exe
forties.obj Roman.obj: Roman.h
forties.exe: forties.obj Roman.obj
	$(CC) $(CFLAGS) forties.obj Roman.obj

namelib: namelib.exe
namelib.exe: contain.h allstack.h
#################################################################
clean:
	del *.obj
	del *.exe
