# Makefile for Appendix B
# Standard Template Library (STL)

CC = bcc32
CFLAGS = -O -P
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

all: find1 algo1 vec1 vec2 list1 list2 deque1 queue1 stack1 map1 ptrlist1
#####################################################################
# Generic Algorithms
find1: find1.exe
algo1: algo1.exe

# Vector
vec1: vec1.exe
vec2: vec2.exe

# List
list1: list1.exe
list2: list2.exe

# Deque
deque1: deque1.exe

# Queue
queue1: queue1.exe

# Stack
stack1: stack1.exe

# Map
map1: map1.exe

# Pointer List
ptrlist1: ptrlist1.exe
ptrlist1.exe: Shape.h
#####################################################################
clean:
	del *.obj
	del *.exe
