# Makefile for Chapter 3 Exercises
# C++ Program Structure

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = itoh1 itoh2 nextday rotate joins names ex7 bmove2 d1 d2 d3 d4

all: $(PGMS)
#################################################################
# Exercise 1
itoh1: itoh1.C

# Exercise 2
itoh2: itoh2.C

# Exercise 3
nextday: nextday.C

# Exercise 4
rotate: rotate.C
	$(CC) $(CFLAGS) -DDRIVER rotate.C -o rotate

# Exercise 5
joins: joins.C

# Exercise 6
names: names.C

# Exercise 7
ex7: ex7.C

# Exercise 8
bmove2: bmove2.C

# Exercise 9
d1: d1.o ndim.o
	$(CC) $(CFLAGS) d1.o ndim.o -o d1
d1.o ndim.o: ndim.h

d2: d2.o ndim.o
	$(CC) $(CFLAGS) d2.o ndim.o -o d2
d2.o ndim.o: ndim.h

d3: d3.o ndim.o
	$(CC) $(CFLAGS) d3.o ndim.o -o d3
d3.o ndim.o: ndim.h

d4: d4.o ndim.o
	$(CC) $(CFLAGS) d4.o ndim.o -o d4
d4.o ndim.o: ndim.h
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
