# Makefile for Chapter 6 Programs
# Overloading

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = classx classy classz date1 date2 point1 point2 maxlen vp1 args \
	  margs1 margs2 cpx int cast1 cast2 cast3 plist2

all: $(PGMS)
#################################################################
# Overloading global/static/member functions
classx: classx.C
classy: classy.C
classz: classz.C
#################################################################
# Default args vs. function overloading
date1: date1.C
date2: date2.C
point1: point1.C
point2: point2.C
#################################################################
# Const * conversions
maxlen: maxlen.C
#################################################################
# Void Pointers
vp1: vp1.C
#################################################################
# Ellipsis Rule
args: args.o Roman.o
	$(CC) $(CFLAGS) args.o Roman.o -o args
args.o Roman.o: Roman.h
#################################################################
# Intersection Rule
margs1: margs1.C
margs2: margs2.C
#################################################################
# Complex class
cpx: Complex.h
#################################################################
# Integer class
int: int.C
	$(CC) $(CFLAGS) int.C -o int -lm
#################################################################
# Overloaded casts
cast1: cast1.C
cast2: cast2.C
cast3: cast3.C
#################################################################
# Smart Pointers
smartp: smartp.C
#################################################################
# List class
plist2: plist2.o List2.o
	$(CC) $(CFLAGS) plist2.o List2.o -o plist2
plist2.o List2.o: List2.h
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
