# Makefile for Chapter 10 Programs
# Template Classes

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = istack tstack store node1 node2 \
block1 block2 kernel gfifo tcomp a1d a1ds a2d a3d font binit mt1 mt2 mt3 \
buf1 buf2 invest1 invest2 fclass pixel nest map zip zip2 plist3 plist4

all: $(PGMS)
#################################################################
# Stack class
istack: StackInt.h
tstack: Stack.h
#################################################################
# Class Instantiations
store: store.o String.o
	$(CC) $(CFLAGS) store.o String.o -o store
store.o: Stack.h String.h
String.o: String.h

node1: node1.o String.o
	$(CC) $(CFLAGS) node1.o String.o -o node1
node1.o: String.h

node2: node2.o String.o
	$(CC) $(CFLAGS) node2.o String.o -o node2
node2.o: String.h
#################################################################
# Template constant expression parameters
binit: binit.C

block1: block1.o String.o
	$(CC) $(CFLAGS) block1.o String.o -o block1
block1.o: String.h Block1.h

block2: block2.o String.o
	$(CC) $(CFLAGS) block2.o String.o -o block2
block2.o: String.h Block2.h
#################################################################
# containment - Fifo class
kernel: kernel.o String.o
	$(CC) $(CFLAGS) kernel.o String.o -o kernel
kernel.o: Stack.h String.h Array.h Array.C

gfifo: gfifo.o String.o
	$(CC) $(CFLAGS) gfifo.o String.o -o gfifo
gfifo.o: Fifo.h String.h Array.h Array.C

tcomp: String.h
#################################################################
# Constant expression parameters
buf1: buf1.o String.o
	$(CC) $(CFLAGS) buf1.o String.o -o buf1
buf1.o: Buffer.h String.h
buf2: Buffer.h Array.h Array.C
#################################################################
# Template friend functions
invest1: invest1.C
invest2: invest2.C
#################################################################
# Template friend classes
fclass: fclass.C
#################################################################
# Template default types
pixel: pixel.o String.o
	$(CC) $(CFLAGS) pixel.o String.o -o pixel
pixel.o: String.h 
#################################################################
# Template nested classes
nest: nest.o String.o
	$(CC) $(CFLAGS) nest.o String.o -o nest
nest.o: String.h Fifo.h Array.h Array.C
#################################################################
# Templates with typedefs and enumerations
font: Buffer.h
#################################################################
# Array classes
a1d: Array.h Array.C
a1ds: Arrays.h Arrays.C
a2d: Array.h Array.C Array2d.h
a3d: Array.h Array.C Array2d.h Array3d.h
#################################################################
# Assoc class
map: map.o String.o
	$(CC) $(CFLAGS) map.o String.o  -o map -lm
map.o: Assoc.h String.h Assoc.C Complex.h Polar.h Array.h Array.C

zip: zip.o String.o
	$(CC) $(CFLAGS) zip.o String.o -o zip
zip.o: Assoc.h Array.h String.h Assoc.C Array.C

zip2: zip2.o String.o
	$(CC) $(CFLAGS) zip2.o String.o -o zip2
zip2.o: Assoc.h Array.h String.h Assoc.C Array.C
#################################################################
# Member Templates
mt1: mt1.o Range.o
	$(CC) $(CFLAGS) mt1.o Range.o -o mt1
mt1.o Range.o: Range.h

mt2: mt2.o String.o
	$(CC) $(CFLAGS) mt2.o String.o -o mt2
mt2.o String.o: String.h

mt3: mt3.o String.o
	$(CC) $(CFLAGS) mt3.o String.o -o mt3
mt3.o String.o: String.h
#################################################################
# List class - Iterators
plist3: plist3.o String.o
	$(CC) $(CFLAGS) plist3.o String.o -o plist3
plist3.o: List.h List.C String.h

plist4: plist4.o String.o
	$(CC) $(CFLAGS) plist4.o String.o -o plist4
plist4.o: List.h List.C String.h
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
