# Makefile for Chapter 7 Exercises
# Class Design

CC = bcc
CFLAGS = -P -O
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

all: cfifo fract menu count rom1 range s1 s2 s3 bit1 bit2
#################################################################
# Exercise 1
cfifo: cfifo.exe
cfifo.exe: cfifo.obj Fifo.obj
	$(CC) $(CFLAGS) cfifo.obj Fifo.obj
cfifo.obj Fifo.obj: Fifo.h

# Exercise 2
fract: fract.exe
fract.exe: Fraction.h

# Exercise 3
menu: menu.exe
menu.exe: menu.obj String.obj
	$(CC) $(CFLAGS) menu.obj String.obj
menu.obj String.obj: String.h

# Exercise 4
count: count.exe

# Exercise 5
rom1: rom1.exe
rom1.exe: rom1.obj roman.obj
	$(CC) $(CFLAGS) rom1.obj roman.obj
rom1.obj roman.obj: Roman.h

# Exercise 6
range: range.exe
range.exe: range.obj Rint.obj
	$(CC) $(CFLAGS) range.obj Rint.obj
range.obj Rint.obj: Rint.h

# Exercise 7
s1: s1.exe
s1.exe: s1.obj String1.obj
	$(CC) $(CFLAGS) s1.obj String1.obj
s1.obj String1.obj: String1.h

# Exercise 8 
s2: s2.obj

# Exercise 9 
s3: s3.exe
s3.exe: s3.obj String3.obj
	$(CC) $(CFLAGS) s3.obj String3.obj
s3.obj String3.obj: String3.h

# Exercise 10 
bit1: bit1.exe
bit1.exe: bit1.obj Bit.obj
	$(CC) $(CFLAGS) bit1.obj Bit.obj
bit1.obj Bit.obj: Bit.h

bit2: bit2.exe
bit2.exe: bit2.obj Bit.obj
	$(CC) $(CFLAGS) bit2.obj Bit.obj
bit2.obj Bit.obj: Bit.h
#################################################################
clean:
	del *.obj
	del *.exe
