# Makefile for Chapter 7 Programs
# Class Design

CC = bcc
CFLAGS = -P -O
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

all: square s1 s2 s3 s4 coins sfriend finance friend1 friend2 \
nt r0 r1 r2 r3 r4 r5 lvrv
#################################################################
# Assignment
square: square.exe
#################################################################
# String class
s1: s1.exe
s1.obj String.obj: String.h
s1.exe: s1.obj String.obj
	$(CC) $(CFLAGS) s1.obj String.obj

s2: s2.exe
s2.obj String.obj: String.h
s2.exe: s2.obj String.obj
	$(CC) $(CFLAGS) s2.obj String.obj

s3: s3.exe
s3.obj String.obj: String.h
s3.exe: s3.obj String.obj
	$(CC) $(CFLAGS) s3.obj String.obj

s4: s4.exe
s4.obj String.obj: String.h
s4.exe: s4.obj String.obj
	$(CC) $(CFLAGS) s4.obj String.obj

lvrv: lvrv.exe
lvrv.exe: lvrv.obj String.obj
	$(CC) $(CFLAGS) lvrv.obj String.obj
lvrv.obj String.obj: String.h
#################################################################
# Friends
coins: coins.exe

sfriend: sfriend.exe
sfriend.obj String2.obj: String2.h
sfriend.exe: sfriend.obj String2.obj
	$(CC) $(CFLAGS) sfriend.obj String2.obj
finance: finance.exe
friend1: friend1.exe
friend2: friend2.exe
#################################################################
# Range Int class
nt: nt.exe
nt.obj Rint.obj: Rint.h
nt.exe: nt.obj Rint.obj
	$(CC) $(CFLAGS) nt.obj Rint.obj

r0: r0.exe
r0.obj Rint.obj: Rint.h
r0.exe: r0.obj Rint.obj
	$(CC) $(CFLAGS) r0.obj Rint.obj

r1: r1.exe
r1.obj Rint.obj: Rint.h
r1.exe: r1.obj Rint.obj
	$(CC) $(CFLAGS) r1.obj Rint.obj

r2: r2.exe
r2.obj Rint.obj: Rint.h
r2.exe: r2.obj Rint.obj
	$(CC) $(CFLAGS) r2.obj Rint.obj

r3: r3.exe
r3.obj Rint.obj: Rint.h
r3.exe: r3.obj Rint.obj
	$(CC) $(CFLAGS) r3.obj Rint.obj

r4: r4.exe
r4.obj Rint.obj: Rint.h
r4.exe: r4.obj Rint.obj
	$(CC) $(CFLAGS) r4.obj Rint.obj

r5: r5.exe
r5.obj Rint.obj: Rint.h
r5.exe: r5.obj Rint.obj
	$(CC) $(CFLAGS) r5.obj Rint.obj
#################################################################
clean:
	del *.obj
	del *.exe
