# Makefile for Chapter 1 Programs
# Getting Started

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: flight customer seat company taxes house vehicle motorh machine \
answer library
#################################################################
# classes, associations
flight: flight.exe
flight.exe: PtrList.h List.h List.C

customer: customer.exe
seat: seat.exe
seat.exe: List.h List.C

# classes, link attributes, roles
company: company.exe
company.exe: company.obj String.obj
	$(CC) $(CFLAGS) company.obj String.obj
company.obj: Array.h Array.C String.h
String.obj: String.h

# classes, qualifications
taxes: taxes.exe
taxes.exe: taxes.obj String.obj
	$(CC) $(CFLAGS) taxes.obj String.obj
taxes.obj: Assoc.h Assoc.C Array.h Array.C String.h

# aggregation
house: house.exe

# generalization
vehicle: vehicle.exe

# multiple inheritance, virtual bases
motorh: motorh.exe
machine: machine.exe

# Exception Handling
answer: answer.exe
answer.exe: answer.obj String.obj
	$(CC) $(CFLAGS) answer.obj String.obj
answer.obj: Message.h List.h List.C PtrList.h String.h

# Object modeling
library: library.exe
library.exe: library.obj String.obj
	$(CC) $(CFLAGS) library.obj String.obj
library.obj: library.h ListCopy.h List.h List.C PtrList.h String.h \
Assoc.h Assoc.C Array.h Array.C
#################################################################
clean:
	del *.obj
	del *.exe
