# Makefile for Chapter 10 Exercises
# Template Classes

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: tstack1 tstack2 a1d a2d newdata gfifo1 gfifo2 gfifo3 \
transp a4d tblock2 fs1 sp1 zip2 zip3 plist na1 na2 na3 bt

#################################################################
# Exercise 1
tstack1: tstack1.exe
tstack1.exe: tstack1.obj String.obj
	$(CC) $(CFLAGS) tstack1.obj String.obj
tstack1.obj: Stack1.h String.h
String.obj: String.h

# Exercise 2
tstack2: tstack2.exe
tstack2.exe: Stack2.h Array.h Array.C

# Exercise 3
a1d: a1d.exe
a1d.exe: Array.h Array.C

a2d: a2d.exe
a2d.exe: Array.h Array.C Array2d.h

# Exercise 4
newdata: newdata.exe
newdata.exe: newdata.obj String.obj
	$(CC) $(CFLAGS) newdata.obj String.obj
newdata.obj: String.h

# Exercise 5
gfifo1: gfifo1.exe
gfifo1.exe: FifoChr.h Fifo.h Array.h Array.C

# Exercise 6
gfifo2: gfifo2.exe
gfifo2.exe: Fifo.h Array.h Array.C

# Exercise 7
gfifo3: gfifo3.exe
gfifo3.exe: gfifo3.obj String.obj
	$(CC) $(CFLAGS) gfifo3.obj String.obj
gfifo3.obj: String.h Fifo2.h List.h List.C

# Exercise 8
transp: transp.exe
transp.exe: transpos.h Array2d.h Array.h Array.C

# Exercise 9
a4d: a4d.exe
a4d.exe: Array4d.h Array3d.h Array2d.h Array.h Array.C

# Exercise 10 
tblock2: tblock2.exe
tblock2.exe: tblock2.obj String.obj
	$(CC) $(CFLAGS) tblock2.obj String.obj
tblock2.obj: String.h Block2.h

# Exercise 11 
fs1: fs1.exe
fs1.exe: FString1.h

# Exercise 12 
sp1: sp1.exe
sp1.exe: sp1.obj String.obj
	$(CC) $(CFLAGS) sp1.obj String.obj
sp1.obj: Ptr.h String.h

# Exercise 13 
zip2: zip2.exe
zip2.exe: zip2.obj String.obj
	$(CC) $(CFLAGS) zip2.obj String.obj
zip2.obj: Assoc2.h Array.h String.h Assoc2.C Array.C

# Exercise 14 
zip3: zip3.exe
zip3.exe: zip3.obj String.obj
	$(CC) $(CFLAGS) zip3.obj String.obj
zip3.obj: Assoc2.h Array.h String.h Assoc2.C Array.C

# Exercise 15 
plist: plist.exe
plist.exe: plist.obj String.obj
	$(CC) $(CFLAGS) plist.obj String.obj
plist.obj: List.h List.C String.h

# Exercise 16
bt: bt.exe
bt.exe: bt.obj String.obj
	$(CC) $(CFLAGS) bt.obj String.obj
bt.obj: String.h Btree.h

# Exercise 17
na1: na1.exe
na1.exe: nArray.h nArray.C

na2: na2.exe
na2.exe: nArray.h nArray.C

na3: na3.exe
na3.exe: nArray.h nArray.C
#################################################################
clean:
	del *.obj
	del *.exe
