# Makefile for Chapter 2 Exercises
# C++ Basics

CC = bcc
CFLAGS = -P -O
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

all: ex1 ex2 ex3 ex4 ex5 ex6 ex7
#################################################################
# Exercise 1
ex1: ex1.exe

# Exercise 2
ex2: ex2.exe

# Exercise 3
ex3: ex3.exe

# Exercise 4
ex4: ex4.exe

# Exercise 5
ex5: ex5.exe

# Exercise 6
ex6: ex6.exe

# Exercise 7
ex7: ex7.exe
#################################################################
clean:
	del *.obj
	del *.exe
