# Makefile for Chapter 14 Programs 
# Multiple Inheritance

CC = bcc
CFLAGS = -P -O -ml
.c.obj:
	$(CC) $(CFLAGS) -c $<
.c.exe:
	$(CC) $(CFLAGS) $<

all: bci ambig dom1 dom2 polym mh1 mh2 mh3 dev1 dev2 dev3 \
fax1 fax2 fax3 fax4 multi1 multi2 multi3 multi4 stack mp1 mp2 v1
#################################################################
# Base class initialization
bci: bci.exe
#################################################################
# Ambiguiies
ambig: ambig.exe
#################################################################
# Dominance
dom1: dom1.exe
dom1.exe: dom1.obj String.obj
	$(CC) $(CFLAGS) dom1.obj String.obj
dom1.obj: String.h
String.obj: String.h

dom2: dom2.exe
dom2.exe: dom2.obj String.obj
	$(CC) $(CFLAGS) dom2.obj String.obj
dom2.obj: String.h
#################################################################
# Polymorphism
polym: polym.exe
#################################################################
# Distinct Base Classes (Pattern 1)
mh1: mh1.exe
mh1.exe: mh1.obj String.obj
	$(CC) $(CFLAGS) mh1.obj String.obj
mh1.obj: Motorhme.h Vehicle.h Resident.h PtrList.h List.h List.C String.h

mh2: mh2.exe
mh2.exe: mh2.obj String.obj
	$(CC) $(CFLAGS) mh2.obj String.obj
mh2.obj: Motorhme.h Vehicle.h Resident.h PtrList.h List.h List.C String.h

mh3: mh3.exe
mh3.exe: mh3.obj String.obj
	$(CC) $(CFLAGS) mh3.obj String.obj
mh3.obj: Motorhme.h Vehicle.h Resident.h PtrList.h List.h List.C String.h
#################################################################
# Multiple Inclusion (Pattern 2)
dev1: dev1.exe
dev1.exe: Device.h PtrList.h List.h List.C

dev2: dev2.exe
dev2.exe: Device.h PtrList.h List.h List.C

dev3: dev3.exe
dev3.exe: Device.h PtrList.h List.h List.C
#################################################################
# Virtual Base Classes (Pattern 3)
fax1: fax1.exe
fax1.exe: fax1.obj String.obj
	$(CC) $(CFLAGS) fax1.obj String.obj
fax1.obj: Machine.h String.h PtrList.h List.h List.C

fax2: fax2.exe
fax2.exe: fax2.obj String.obj
	$(CC) $(CFLAGS) fax2.obj String.obj
fax2.obj: Machine2.h String.h PtrList.h List.h List.C

fax3: fax3.exe
fax3.exe: fax3.obj String.obj
	$(CC) $(CFLAGS) fax3.obj String.obj
fax3.obj: Machine.h String.h PtrList.h List.h List.C

fax4: fax4.exe
fax4.exe: fax4.obj String.obj
	$(CC) $(CFLAGS) fax4.obj String.obj
fax4.obj: Machine3.h String.h PtrList.h List.h List.C
#################################################################
# Multiple Inheritance Programs
multi1: multi1.exe
multi1.exe: Multi1.h 

multi2: multi2.exe
multi2.exe: Multi2.h 

multi3: multi3.exe
multi3.exe: Multi3.h 

multi4: multi4.exe
multi4.exe: Multi4.h 
#################################################################
# Stack - Bounded (Array) & Unbounded (List) stack
stack: stack.exe
stack.exe: stack.obj String.obj
	$(CC) $(CFLAGS) stack.obj String.obj
stack.obj: Stack.h UBstack.h BStack.h Array.h Array.C String.h List.h List.C
#################################################################
# Multiple inheritance, Persistent Strings and Shapes
mp1: mp1.exe
mp1.exe: mp1.obj persist.obj String.obj
	$(CC) $(CFLAGS) mp1.obj persist.obj String.obj
mp1.obj: PShape.h Shape.h List.h List.C PtrList.h String.h \
Assoc.h Assoc.C Array.h Array.C Persist.h PString.h
persist.obj: PShape.h Shape.h Persist.h PString.h String.h persist.C

mp2: mp2.exe
mp2.exe: mp2.obj persist.obj String.obj
	$(CC) $(CFLAGS) mp2.obj persist.obj String.obj
mp2.obj: PShape.h Shape.h List.h List.C PtrList.h String.h \
Assoc.h Assoc.C Array.h Array.C Persist.h PString.h
#################################################################
# Multiple Inheritance Virtual Function Implementaion
v1: v1.exe
v1.exe: V1.h
#################################################################
clean:
	del *.obj
	del *.exe
