# Makefile for Chapter 13 Exercises
# Exception Handling

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = avg mycp1 mycp2 fract s1 arrays slope

all: $(PGMS)
#################################################################
# Exercise 1
avg: Double.h

# Exercise 2
mycp1: mycp1.o String.o
	$(CC) $(CFLAGS) mycp1.o String.o -o mycp1
mycp1.o: File1.h FilePtr.h String.h
String.o: String.h

# Exercise 3
mycp2: mycp2.o String.o
	$(CC) $(CFLAGS) mycp2.o String.o -o mycp2
mycp2.o: File2.h FilePtr.h String.h

# Exercise 4
fract: Fraction.h

# Exercise 5
s1: s1.o String.o
	$(CC) $(CFLAGS) s1.o String.o -o s1
s1.o: String.h

# Exercise 6
arrays: autoptr.h

# Exercise 7
slope: slope.o String.o
	$(CC) $(CFLAGS) slope.o String.o -o slope
slope.o: Point5.h Line.h String.h
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
