# Makefile for Chapter 4 Exercises
# Classes

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: dates cfifo5 rnum2 rnum3 cfifo6 record2 points
#################################################################
# Exercise 1
dates: dates.exe
dates.obj date.obj: date.h
dates.exe: dates.obj date.obj
	$(CC) $(CFLAGS) dates.obj date.obj

# Exercise 2
cfifo5: cfifo5.exe
cfifo5.obj fifo5.obj: fifo5.h
cfifo5.exe: cfifo5.obj fifo5.obj
	$(CC) $(CFLAGS) cfifo5.obj fifo5.obj

# Exercise 3
rnum2: rnum2.exe
rnum2.obj Roman2.obj: Roman2.h
rnum2.exe: rnum2.obj Roman2.obj
	$(CC) $(CFLAGS) rnum2.obj Roman2.obj

# Exercise 4
rnum3: rnum3.exe
rnum3.obj Roman3.obj: Roman3.h
rnum3.exe: rnum3.obj Roman3.obj
	$(CC) $(CFLAGS) rnum3.obj Roman3.obj

# Exercise 5
cfifo6: cfifo6.exe
cfifo6.obj fifo6.obj: fifo6.h
cfifo6.exe: cfifo6.obj fifo6.obj
	$(CC) $(CFLAGS) cfifo6.obj fifo6.obj

# Exercise 6
record2: record2.exe
record2.obj: record2.h stringn.h
record2.exe: record2.obj stringn.obj
	$(CC) $(CFLAGS) record2.obj stringn.obj

# Exercise 7 
points: points.exe
points.obj point6.obj: point6.h
points.exe: points.obj point6.obj
	$(CC) $(CFLAGS) points.obj point6.obj
#################################################################
clean:
	del *.obj
	del *.exe
