# Makefile for Chapter 9 Programs
# Template Functions

CC = CC
CFLAGS = -O -ptused -n32 -experimental
.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = max1 max2 max3 max4 max5 tf1 tf2 exports swap eqsize countval \
ptf1 ptf2 ptf3 memset dim2 dim2s transp

all: $(PGMS)
#################################################################
# max() template functions
max1: max1.C

max2: max2.o String.o
	$(CC) $(CFLAGS) max2.o String.o -o max2
max2.o String.o: String.h

max3: max3.o String.o
	$(CC) $(CFLAGS) max3.o String.o -o max3
max3.o String.o: String.h

max4: max4.o String.o
	$(CC) $(CFLAGS) max4.o String.o -o max4
max4.o String.o: String.h
#################################################################
# template functions
tf1: tf1.C
tf2: tf2.C
countval: countval.o String.o
	$(CC) $(CFLAGS) countval.o String.o -o countval
exports: exports.o defs.o
	$(CC) $(CFLAGS) exports.o defs.o -o exports
exports.o defs.o: defs.h
#################################################################
# swap(), eqsize() template functions
swap: swap.o String.o
	$(CC) $(CFLAGS) swap.o String.o -o swap
swap.o String.o: String.h

eqsize: eqsize.o String.o
	$(CC) $(CFLAGS) eqsize.o String.o -o eqsize
eqsize.o String.o: String.h
#################################################################
# ptf(), pointers to functions
ptf1: ptf1.C

ptf2: ptf2.o String.o
	$(CC) $(CFLAGS) ptf2.o String.o -o ptf2
ptf2.o String.o: String.h

ptf3: ptf3.o String.o
	$(CC) $(CFLAGS) ptf3.o String.o -o ptf3
ptf3.o String.o: String.h
#################################################################
# overloading template functions
ov1: ov1.o String.o
	$(CC) $(CFLAGS) ov1.o String.o -o ov1
ov1.o String.o: String.h
#################################################################
# specializing template functions
spm: spm.C

max5: max5.o String.o
	$(CC) $(CFLAGS) max5.o String.o -o max5
max5.o String.o: String.h

memset: memset.o String.o
	$(CC) $(CFLAGS) memset.o String.o -o memset
memset.o String.o: String.h Complex.h
#################################################################
# dim2() template function
# Two-dimensional arrays at run time
dim2: dim2.h
dim2s: dim2.h Complex.h
#################################################################
# transpose() template function
transp: transp.o String.o
	$(CC) $(CFLAGS) transp.o String.o -o transp
String.o: String.h
transp.o: String.h dim2.h transpos.h
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
