# Makefile for Chapter 13 Exercises
# Exception Handling

CC = cl
CFLAGS = -O -GX -GR -nologo
.c.obj:
	$(CC) $(CFLAGS) -c -Tp $<
.c.exe:
	$(CC) $(CFLAGS) -Tp $<

all: avg mycp1 mycp2 fract s1 arrays slope
#################################################################
# Exercise 1
avg: avg.exe
avg.exe: Double.h

# Exercise 2
mycp1: mycp1.exe
mycp1.exe: mycp1.obj String.obj
	$(CC) $(CFLAGS) mycp1.obj String.obj
mycp1.obj: File1.h FilePtr.h String.h except.h
String.obj: String.h

# Exercise 3
mycp2: mycp2.exe
mycp2.exe: mycp2.obj String.obj
	$(CC) $(CFLAGS) mycp2.obj String.obj
mycp2.obj: File2.h FilePtr.h String.h except.h

# Exercise 4
fract: fract.exe
fract.exe: Fraction.h

# Exercise 5
s1: s1.exe
s1.exe: s1.obj String.obj
	$(CC) $(CFLAGS) s1.obj String.obj
s1.obj: String.h except.h

# Exercise 6
arrays: arrays.exe
arrays.exe: autoptr.h

# Exercise 7
slope: slope.exe
slope.exe: slope.obj String.obj
	$(CC) $(CFLAGS) slope.obj String.obj
slope.obj: Point5.h Line.h String.h except.h
#################################################################
clean:
	del *.obj
	del *.exe
