# Makefile for Appendix A
# IOstream Library

CC = CC
CFLAGS = -O -ptused -n32 -experimental

.C.o:
	$(CC) $(CFLAGS) -c $<
.C:
	$(CC) $(CFLAGS) $< -o $@

PGMS = ts1 ex1 ex2 ex3 ex4 ioprec readf writef replace append \
wordcnt t1 t2 t3 t4

all: $(PGMS)
#################################################################
ts1: ts1.C

ex1: ex1.C
ex2: ex2.C
ex3: ex3.C
ex4: ex4.C

t1: t1.C
t2: t2.C
t3: t3.C
t4: t4.C

wordcnt: wordcnt.C
wordcnt2: wordcnt2.C
wordcnt3: wordcnt3.C

ioprec: ioprec.C

writef: writef.C Hue.h

readf: readf.C Hue.h

replace: replace.C Hue.h

append: append.C Hue.h
#################################################################
clean:
	rm -rf $(PGMS)
	rm -rf a.out core *.o ii_files
